apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: mart
      username: student
      tlsSkipVerify: true
    secureJsonData:
      password: student
